server:
  port: 8082

spring:
  application:
    name: job-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/hirenow
      database: hirenow_jobs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka